//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bins_PcQuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_control
    {
        public int id { get; set; }
        public string business_type { get; set; }
        public int is_running { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
        public string logs { get; set; }
    }
}
