//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bins_PcQuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class quick_app_info
    {
        public int id { get; set; }
        public string path { get; set; }
        public string title { get; set; }
        public string pc_name { get; set; }
        public int is_test { get; set; }
        public int is_del { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
